name: Build and Deploy Vue Application to Github Pages
on:
    [push]:
        branch: master
jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy-Vue
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm ci
    - run: npm test
    - run: npm run build
    - uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: marianissimus
        reponame: agenda
        token: ${{ secrets.GITHUB_TOKEN }} # no need to change this line this is used to create the branch in your application repository
